#include "sim/sim_pic.h"
#include <string.h>
#include "sim/sim_state.h"

static uint8_t pick(const SimPicState *s) {
    unsigned i, l, stop = 8u;
    if (!s) return 0xFFu;
    for (i=0;i<8;i++) { l=(s->priority_add+i)&7u; if((s->isr&(1u<<l))&&!(s->special_fully_nested&&l==s->cascade_line)&&!(s->special_mask_mode&&(s->imr&(1u<<l)))){stop=i;break;} }
    for (i=0;i<stop;i++) { l=(s->priority_add+i)&7u; if((s->irr&(1u<<l))&&!(s->imr&(1u<<l))) return (uint8_t)l; }
    return 0xFFu;
}
static uint8_t request_byte(const SimBusRequest *request) { return request->byte_enable == SIM_BUS_BYTE_ENABLE_HIGH ? (uint8_t)(request->data >> 8u) : (uint8_t)request->data; }
static uint16_t response_byte(const SimBusRequest *request, uint8_t value) { return request->byte_enable == SIM_BUS_BYTE_ENABLE_HIGH ? (uint16_t)((uint16_t)value << 8u) : value; }
const SimPicState *sim_pic_current_state(const SimPic *p,const SimState *s) { return p&&p->attached?(const SimPicState*)sim_state_region_current_const(s,p->state_region):NULL; }
uint8_t sim_pic_pending(const SimPic *p,const SimState *s) { return pick(sim_pic_current_state(p,s)); }
void sim_pic_init(SimPic *p) { if(!p)return;memset(p,0,sizeof(*p));p->command_port=0x20u;p->data_port=0x21u; }
void sim_pic_reset(SimPic *p) { if(p)p->driven_irq_lines=0; }
void sim_pic_set_irq_lines(SimPic *p,uint8_t l) { if(p)p->driven_irq_lines=l; }
void sim_pic_set_irq_line(SimPic *p,unsigned n,bool high) { if(!p||n>7)return;if(high)p->driven_irq_lines|=(uint8_t)(1u<<n);else p->driven_irq_lines&=(uint8_t)~(1u<<n); }
void sim_pic_pulse_irq(SimPic *p,unsigned n) { sim_pic_set_irq_line(p,n,true); }
void sim_pic_set_ports(SimPic *p,uint16_t command,uint16_t data) { if(p){p->command_port=command;p->data_port=data;} }
void sim_pic_connect_slave(SimPic *master,SimPic *slave,unsigned line) { if(master&&slave&&line<8u){master->slave=slave;master->cascade_line=(uint8_t)line;slave->cascaded=true;} }
static bool probe(void *i,const SimBusRequest *r) { SimPic *p=i;return p&&r&&r->valid&&(r->kind==SIM_BUS_INTERRUPT_ACK||(r->kind==SIM_BUS_IO&&(r->address==p->command_port||r->address==p->data_port))); }
static void evaluate(void *i,const SimState *c,const SimBusState *t,SimBusResponse *r) { SimPic *p=i;const SimPicState*s=sim_pic_current_state(p,c);const SimPicState*child;uint8_t l;if(!s||!t||!r)return;r->ready=true;if(t->request.kind==SIM_BUS_INTERRUPT_ACK){l=s->pending_inta_level==0xFFu?pick(s):s->pending_inta_level;child=p->slave?sim_pic_current_state(p->slave,c):NULL;if(s->inta_phase&&child!=NULL&&l==p->cascade_line){l=child->pending_inta_level==0xFFu?7u:child->pending_inta_level;r->data=(uint16_t)(child->vector_base+l);}else r->data=s->inta_phase?(uint16_t)(s->vector_base+(l==0xFFu?7u:l)):0u;}else if(t->request.direction==SIM_BUS_READ){if(t->request.address==p->command_port&&s->poll){l=pick(s);r->data=response_byte(&t->request,l==0xFFu?0u:(uint8_t)(0x80u|l));}else r->data=response_byte(&t->request,t->request.address==p->command_port?(s->read_select_isr?s->isr:s->irr):s->imr);} }
static void eoi(SimPicState*s,uint8_t v){unsigned i,l=0;if(v&0x40u){l=v&7u;s->isr&=(uint8_t)~(1u<<l);}else for(i=0;i<8;i++){l=(s->priority_add+i)&7u;if(s->isr&(1u<<l)){s->isr&=(uint8_t)~(1u<<l);break;}}if(v&0x80u)s->priority_add=(uint8_t)((l+1u)&7u);}
static void command(SimPicState*s,uint8_t v){if(v&0x10u){s->irr=s->imr=s->isr=0;s->icw_step=2;s->single=(v&2u)!=0;s->expect_icw4=(v&1u)!=0;s->level_triggered=(v&8u)!=0;s->initialized=false;s->pending_inta_level=0xFFu;s->rotate_auto_eoi=false;}else if((v&0x18u)==0x08u){s->poll=(v&4u)!=0;s->read_select_isr=(v&2u)!=0;if(v&0x20u)s->special_mask_mode=(v&0x40u)!=0;}else if((v&0x18u)==0u){if(v&0x20u)eoi(s,v);else if((v&0xC0u)==0xC0u)s->priority_add=(uint8_t)((v+1u)&7u);else if((v&0xC0u)==0x80u)s->rotate_auto_eoi=true;else if((v&0xC0u)==0x00u)s->rotate_auto_eoi=false;}}
static void commit(void*i,const SimState*c,SimState*n,const SimBusRequest*r,const SimBusResponse*x){SimPic*p=i;const SimPicState*old=sim_pic_current_state(p,c);SimPicState*s=p?(SimPicState*)sim_state_region_next(n,p->state_region):NULL;SimPicState*child_next;const SimPicState*child_old;uint8_t v,l;(void)x;if(!old||!s||!r)return;if(r->kind==SIM_BUS_INTERRUPT_ACK){child_old=p->slave?sim_pic_current_state(p->slave,c):NULL;child_next=p->slave?(SimPicState*)sim_state_region_next(n,p->slave->state_region):NULL;if(!old->inta_phase){s->pending_inta_level=pick(old);if(s->pending_inta_level!=0xFFu){s->irr&=(uint8_t)~(1u<<s->pending_inta_level);s->isr|=(uint8_t)(1u<<s->pending_inta_level);}if(child_old&&child_next&&s->pending_inta_level==p->cascade_line){child_next->pending_inta_level=pick(child_old);if(child_next->pending_inta_level!=0xFFu){child_next->irr&=(uint8_t)~(1u<<child_next->pending_inta_level);child_next->isr|=(uint8_t)(1u<<child_next->pending_inta_level);}child_next->inta_phase=1u;}s->inta_phase=1u;}else{if(s->auto_eoi&&s->pending_inta_level!=0xFFu){s->isr&=(uint8_t)~(1u<<s->pending_inta_level);if(s->rotate_auto_eoi)s->priority_add=(uint8_t)((s->pending_inta_level+1u)&7u);}if(child_old&&child_next&&s->pending_inta_level==p->cascade_line){if(child_next->auto_eoi&&child_next->pending_inta_level!=0xFFu){child_next->isr&=(uint8_t)~(1u<<child_next->pending_inta_level);if(child_next->rotate_auto_eoi)child_next->priority_add=(uint8_t)((child_next->pending_inta_level+1u)&7u);}child_next->inta_phase=0;child_next->pending_inta_level=0xFFu;}s->inta_phase=0;s->pending_inta_level=0xFFu;}return;}if(r->direction==SIM_BUS_READ){if(r->address==p->command_port&&old->poll){l=pick(old);if(l!=0xFFu){s->irr&=(uint8_t)~(1u<<l);s->isr|=(uint8_t)(1u<<l);}s->poll=false;}return;}v=request_byte(r);if(r->address==p->command_port){command(s,v);return;}if(s->icw_step==2u){s->vector_base=v&0xF8u;s->icw_step=s->single?(s->expect_icw4?4u:0u):3u;s->initialized=s->single&&!s->expect_icw4;}else if(s->icw_step==3u){s->icw3=v;s->icw_step=s->expect_icw4?4u:0u;s->initialized=!s->expect_icw4;}else if(s->icw_step==4u){s->auto_eoi=(v&2u)!=0;s->buffered=(v&8u)!=0;s->special_fully_nested=(v&16u)!=0;s->icw_step=0;s->initialized=true;}else s->imr=v;}
static void drive(void*i,const SimState*c,SimCycleDrive*d){SimPic*p=i;if(d&&p&&!p->cascaded&&pick(sim_pic_current_state(p,c))!=0xFFu)d->irq_lines|=1u;}
static void sample(void*i,const SimState*c,SimState*n,const SimCycleResolution*r){SimPic*p=i;const SimPicState*o=sim_pic_current_state(p,c);const SimPicState*child;SimPicState*s;uint8_t rise;(void)r;if(!p||!o)return;s=(SimPicState*)sim_state_region_next(n,p->state_region);s->input_lines=p->driven_irq_lines;child=p->slave?sim_pic_current_state(p->slave,c):NULL;if(child&&pick(child)!=0xFFu)s->input_lines|=(uint8_t)(1u<<p->cascade_line);rise=(uint8_t)(s->input_lines&~o->previous_input_lines);if(s->level_triggered)s->irr=s->input_lines;else s->irr|=rise;s->previous_input_lines=s->input_lines;}
static void reset(void*i,SimState*s){SimPic*p=i;SimPicState v={0};if(!p)return;v.vector_base=0x08u;v.cascade_line=p->cascade_line;v.pending_inta_level=0xFFu;*(SimPicState*)sim_state_region_current(s,p->state_region)=v;*(SimPicState*)sim_state_region_next(s,p->state_region)=v;}
SimBusTarget sim_pic_bus_target(SimPic*p,const char*n,uint32_t id){SimBusTarget t={0};t.name=n;t.target_id=id;t.instance=p;t.probe=probe;t.evaluate=evaluate;t.commit=commit;return t;}
bool sim_pic_attach(SimPic*p,SimKernel*k){SimModule m={0};SimPicState v={0};if(!p||!k||p->attached)return false;v.vector_base=0x08u;v.cascade_line=p->cascade_line;v.pending_inta_level=0xFFu;if(!sim_state_add_region(k->state,"pic8259",sizeof(v),&v,&p->state_region))return false;p->attached=true;m.name="pic8259";m.instance=p;m.reset=reset;m.drive=drive;m.sample=sample;return sim_kernel_attach_module(k,&m);}
